<h1> Introduction to Numpy Arrays </h1>
NumPy v1.19

1.   [Getting started](https://numpy.org/doc/stable/reference/generated/numpy.array.html)
2.   Numpy array to represent vecto

To learn Numpy: [Quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html)


## Getting started


Numpy arrays are great alternatives to Python Lists. Some of the key advantages of Numpy arrays are that they are fast, easy to work with, and give users the opportunity to perform calculations across entire arrays.

In the following example, you will first create two Python lists. Then, you will import the numpy package and create numpy arrays out of the newly created lists.*italicized text*

In [ ]:
# Create 2 new lists height and weight
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

# Import the numpy package as np
import numpy as np

# Create 2 numpy arrays from height and weight
np_height = np.array(height)
np_weight = np.array(weight)

## Numpy Array to represent vector

### What is a Vector?
A vector is a tuple of one or more values called scalars.

*Vectors are built from components, which are ordinary numbers. You can think of a vector as a list of numbers, and vector algebra as operations performed on the numbers in the list.*
*   Vectors are often represented using a lowercase character such as “v”; for example: *v = (v1, v2, v3) Where v1, v2, v3 are scalar values, often real values*.
*   Vectors are also shown using a vertical representation or a column; for example:
$$
V =
\begin{pmatrix}
v_1 \\
v_2 \\
v_3 \\
\end{pmatrix}
$$

In [ ]:
# create a vector
from numpy import array
v = array([1, 2, 3])
print(v)

[1 2 3]


### Vector Arithmetic

All operations are performed element-wise between two vectors of equal length to result in a new vector with the same length.

#### Vector Addition
Two vectors of equal length can be added together to create a new third vector.

c = a + b

The new vector has the same length as the other two vectors. Each element of the new vector is calculated as the addition of the elements of the other vectors at the same index; for example:

a + b = (a1 + b1, a2 + b2, a3 + b3)

Or, put another way:

c[0] = a[0] + b[0] <br/>
c[1] = a[1] + b[1] <br />
c[2] = a[2] + b[2] <br />

We can add vectors directly in Python by adding NumPy arrays.

In [ ]:
# add vectors
from numpy import array
a = array([1, 2, 3])
print('Vector a', a)
b = array([1, 2, 3])
print('Vector b', b)
c = a + b
print(c)

Vector a [1 2 3]
Vector b [1 2 3]
[2 4 6]


#### Vector Subtraction

One vector can be subtracted from another vector of equal length to create a new third vector.

c = a - b

As with addition, the new vector has the same length as the parent vectors and each element of the new vector is calculated as the subtraction of the elements at the same indices.

a - b = (a1 - b1, a2 - b2, a3 - b3)

Or, put another way:

c[0] = a[0] - b[0] <br />
c[1] = a[1] - b[1] <br />
c[2] = a[2] - b[2] <br />

The NumPy arrays can be directly subtracted in Python.

In [ ]:
# subtract vectors
from numpy import array
a = array([1, 2, 3])
# print(a)
b = array([0.5, 0.5, 0.5])
# print(b)
c = a - b
print('Sustruction (a - b): ', c)

Sustruction (a - b):  [0.5 1.5 2.5]


#### Vector Multiplication

Two vectors of equal length can be multiplied together.
c = a * b

As with addition and subtraction, this operation is performed element-wise to result in a new vector of the same length.

a * b = (a1 * b1, a2 * b2, a3 * b3)
**or**
ab = (a1b1, a2b2, a3b3)


In [ ]:
# multiply vectors
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([1, 2, 3])
print(b)
c = a * b
print(c)

[1 2 3]
[1 2 3]
[1 4 9]


#### Vector Division

Two vectors of equal length can be divided.
c = a / b

In [ ]:
# divide vectors
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([1, 2, 3])
print(b)
c = a / b
print(c)

[1 2 3]
[1 2 3]
[1. 1. 1.]


#### Vector Dot Product
We can calculate the sum of the multiplied elements of two vectors of the same length to give a scalar.

This is called the dot product, named because of the dot operator used when describing the operation.

*The dot product is the key tool for calculating vector projections, vector decompositions, and determining orthogonality. The name dot product comes from the symbol used to denote it.*

c = a . b
a . b = (a1 * b1 + a2 * b2 + a3 * b3)
a . b = (a1b1 + a2b2 + a3b3)

We can calculate the dot product between two vectors in Python using the dot() function on a NumPy array.

In [ ]:
# dot product vectors
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([1, 2, 3])
print(b)
c = a.dot(b)
print(c)

[1 2 3]
[1 2 3]
14


#### Vector-Scalar Multiplication

A vector can be multiplied by a scalar, in effect scaling the magnitude of the vector.

To keep notation simple, we will use lowercase “s” to represent the scalar value.

c = s * v
or
c = sv

The multiplication is performed on each element of the vector to result in a new scaled vector of the same length.
s * v = (s * v1, s * v2, s * v3)

Or, put another way:

c[0] = a[0] * s <br />
c[1] = a[1] * s <br />
c[2] = a[2] * s <br />


In [ ]:
# vector-scalar multiplication
from numpy import array
a = array([1, 2, 3])
print(a)
s = 0.5
print(s)
c = s * a
print(c)

[1 2 3]
0.5
[0.5 1.  1.5]
